name: Fx.Rotate
author: arieh
category: Effects
tags: [rotation, transform, matrix, styles, fx]
demo: http://tests.arieh.co.il/rotate.html
current: 0.3.1
#docs: http://moodocs.net/arieh/date-range/daterange