name: Fx.Rotate
author: arieh
category: Fx
tags: [rotation, transform, matrix, styles, effects]
#demo: http://arieh.github.com/Mootools-DateRange/
current: 0.1
#docs: http://moodocs.net/arieh/date-range/daterange